import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | Kunfa.AI',
  description: 'Kunfa.AI Terms of Service — AI-powered venture intelligence platform by Metronome FZ-LLC.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="border-b border-gray-200 bg-white">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#0168FE] flex items-center justify-center">
              <span className="text-white font-bold text-lg">K</span>
            </div>
            <span className="font-bold text-lg text-gray-900">Kunfa.AI</span>
          </Link>
          <Link href="/privacy" className="text-sm text-gray-500 hover:text-gray-900 transition">
            Privacy Policy
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-12">Last updated: March 9, 2026</p>

        <div className="prose prose-gray max-w-none space-y-8 text-gray-700 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Platform Description</h2>
            <p>
              Kunfa.AI (&ldquo;the Platform&rdquo;) is an AI-powered venture intelligence platform operated by Metronome FZ-LLC, a company registered in Dubai, UAE. The Platform enables startups to receive AI-generated investment readiness assessments and enables investors to discover, evaluate, and manage deal flow. By accessing or using the Platform, you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. User Accounts and Roles</h2>
            <p>
              The Platform supports two user roles:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li><strong>Startups</strong> may create accounts to submit pitch decks and financial documents for AI scoring, create public company profiles, and receive investment readiness reports.</li>
              <li><strong>Investors</strong> may create accounts to browse company profiles, manage deal pipelines, watchlist companies, and access submitted documents from companies in their pipeline or watchlist.</li>
            </ul>
            <p className="mt-3">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information during registration.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Data Submission and Accuracy</h2>
            <p>
              By submitting information to the Platform, including but not limited to pitch decks, financial documents, company details, and personal information, you represent and warrant that:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>All information provided is accurate, truthful, and self-reported to the best of your knowledge.</li>
              <li>You have the right and authority to submit such information.</li>
              <li>The submission does not infringe upon any third-party intellectual property rights, confidentiality obligations, or contractual restrictions.</li>
            </ul>
            <p className="mt-3">
              All submitted data is subject to due diligence by interested investors. Metronome FZ-LLC does not independently verify the accuracy of user-submitted information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. AI Scoring Disclaimer</h2>
            <p>
              The Kunfa Score and all AI-generated assessments, grades, analyses, and recommendations provided by the Platform are generated by artificial intelligence models and are <strong>informational only</strong>. They do not constitute investment advice, financial advice, legal advice, or any professional recommendation.
            </p>
            <p className="mt-3">
              AI-generated scores should not be relied upon as the sole basis for any investment decision. Users should conduct their own independent due diligence and consult qualified professionals before making investment decisions. Metronome FZ-LLC makes no guarantee regarding the accuracy, completeness, or reliability of AI-generated assessments.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Intellectual Property</h2>
            <p>
              <strong>Your content:</strong> You retain full ownership of all documents, data, and materials you upload to the Platform, including pitch decks, financial documents, and company information. By uploading content, you grant Metronome FZ-LLC a limited, non-exclusive, non-transferable license to process your documents solely for the purpose of generating AI-powered scoring and analysis. This license does not extend to any other use of your documents.
            </p>
            <p className="mt-3">
              <strong>Platform content:</strong> The Kunfa.AI platform, including its design, features, scoring algorithms, and generated reports, is the intellectual property of Metronome FZ-LLC. You may not reproduce, modify, distribute, or create derivative works based on Platform content without prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Payment Terms</h2>
            <p>
              Certain features of the Platform require payment:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li><strong>Kunfa Readiness Report:</strong> A detailed AI-generated investment analysis report is available for $59 USD per submission. Payment is processed securely via Stripe.</li>
              <li>All payments are final and <strong>non-refundable</strong> once a report has been generated and delivered.</li>
              <li>Prices are subject to change with reasonable notice. Existing purchases will not be affected by price changes.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Data Sharing and Visibility</h2>
            <p>
              By creating a company profile on the Platform, you acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Your company profile (including company name, description, industry, stage, score, and other non-confidential details) will be publicly visible to all Platform users.</li>
              <li>Uploaded pitch decks and financial documents are <strong>not publicly accessible</strong>. Access to these documents is restricted to: (a) the startup that uploaded them; (b) authenticated investors who have added the company to their pipeline or watchlist.</li>
              <li>Metronome FZ-LLC may use aggregated, anonymized data for platform analytics and improvement purposes.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Use the Platform for any unlawful purpose or in violation of applicable laws and regulations.</li>
              <li>Submit false, misleading, or fraudulent information.</li>
              <li>Attempt to gain unauthorized access to other users&apos; accounts, documents, or data.</li>
              <li>Interfere with or disrupt the Platform&apos;s operation, including through automated requests, scraping, or denial-of-service attacks.</li>
              <li>Redistribute, resell, or commercially exploit any AI-generated content or reports from the Platform without authorization.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, Metronome FZ-LLC, its directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, business opportunities, or goodwill, arising from your use of or inability to use the Platform.
            </p>
            <p className="mt-3">
              The Platform is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. In no event shall our total liability exceed the amount you have paid to us in the twelve (12) months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Termination and Account Deletion</h2>
            <p>
              You may request deletion of your account and associated data at any time by contacting us at <a href="mailto:hello@vitality.capital" className="text-[#0168FE] hover:underline">hello@vitality.capital</a>. We reserve the right to suspend or terminate accounts that violate these Terms, without prior notice.
            </p>
            <p className="mt-3">
              Upon account deletion, your personal data and uploaded documents will be removed from the Platform within 30 days, except where retention is required by law or for legitimate business purposes (such as maintaining generated reports for paying customers).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Modifications</h2>
            <p>
              We may update these Terms from time to time. Material changes will be communicated via email or prominent notice on the Platform. Your continued use of the Platform after such changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the United Arab Emirates as applied in the Emirate of Dubai, without regard to conflict of law principles. Any disputes arising from or related to these Terms or the Platform shall be subject to the exclusive jurisdiction of the courts of Dubai, UAE, or the DIFC Courts where applicable.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">13. Contact</h2>
            <p>
              For questions about these Terms, please contact:
            </p>
            <p className="mt-2">
              <strong>Metronome FZ-LLC</strong><br />
              Dubai, United Arab Emirates<br />
              Email: <a href="mailto:hello@vitality.capital" className="text-[#0168FE] hover:underline">hello@vitality.capital</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
